// webapp/src/components/Navbar.vue
<template lang="pug">
nav.bg-gray-800
  .mx-auto.max-w-7xl.px-2(class="sm:px-6 lg:px-8")
    .relative.flex.h-16.items-center.justify-between
      .flex.flex-shrink-0.items-center
        img.block.h-16.w-auto(src="/favicon.ico" alt="can it run doom?")

      .flex.flex-3.items-center.justify-center(class="sm:items-stretch sm:justify-start")
        .flex.space-x-4.pl-10
          router-link.nav-btn.bg-gray-900e(
            v-for="r in routes"
            :to="r.path"
            :key="`route_btn_${r.name}`"
            :href="r.path"
            :aria-current="$route?.name"
            :class="$route?.name?.toLowerCase() === r.name.toLowerCase() ? 'active' : ''"
          ) {{ $t(r.localeVar) }}

      .flex.justify-end.items-center.pr-5
        select.form-select.dropdown.nav-btn(v-model="$i18n.locale")
          option(
            v-for="locale in $i18n.availableLocales"
            :key="`locale-${locale}`"
            :value="locale"
            @click="setLocale(locale)"
          ) {{locale.toUpperCase()}}

        .w-12.nav-icon
          img.block.h-6.w-auto.rounded-full(
            class="sm:ml-4"
            src="@/assets/icons/github-mark-white.png"
            alt="source code?"
            @click="onSourceCodeClick"
          )

        .w-12.nav-icon
          img.block.h-6.w-auto.rounded-full(
            class="sm:ml-4"
            src="@/assets/icons/discord-48.png"
            alt="discord server"
            @click="onJoinDiscordClick"
          )

</template>


<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useI18n } from "vue-i18n"
import { useUXStore } from '@/stores'
import { useCookies } from "vue3-cookies"

const { cookies } = useCookies()
const uxStore = computed(() => useUXStore())
const currentLocale = computed(() => uxStore.value.currentLocale)


const routes = [
  { localeVar: 'buttons.routes.home',  name: 'Home', path: '/' },
  { localeVar: 'buttons.routes.bounty',  name: 'Bounty', path: '/bounty' },
]

const i18n = useI18n()

onMounted(() => {
  const sysLang = cookies.get('lang') || 'en'
  if (i18n.availableLocales.indexOf(sysLang) >= 0)
    uxStore.value.setLocale(sysLang)
  i18n.locale.value = sysLang
})

function setLocale(target: string) {
  uxStore.value.setLocale(target)
  i18n.locale.value = target
  cookies.set('lang', target)
}


function onSourceCodeClick() {
  // @ts-ignore
  const url = import.meta.env.VITE_SOURCE_CODE_URL
  window.open(url, '_blank')
}


function onJoinDiscordClick() {
  // @ts-ignore
  const url = import.meta.env.VITE_DISCORD_URL
  window.open(url, '_blank')
}

</script>


<style lang="scss" scoped>
@import '@/assets/styles/doom.scss';

.nav-btn {
  padding: 9px 12px 9px 12px;
  border-radius: 5px;
  text-shadow: $doomTextShadowDanger;
  transition: 0.1s linear;

  &:hover, &.active {
    color: $doomColorSecondary;
    background-color: $doomColorAlt;
    text-shadow: none;
    font-weight: 700;
    letter-spacing: 3px;
  }
} // .nav-btn

.form-select {
  cursor: pointer;
  background-color: transparent;
  border: none;
  color: inherit;
  padding: 5px;
  width: 55px;

  & > option {
    padding: 10px;
    color: black;
  }

  &:focus {
    box-shadow: none;
  }
}

.nav-icon {
  cursor: pointer;

  img {
    transition: 0.1s ease-in, 0.2s ease-out;
  }

  .text {
    opacity: 0;
  }

  &:hover > img {
    box-shadow: $doomBoxShadowDanger;
    height: 1.8rem;
  }
}
</style>

// webapp/src/components/Menus/Navbar.tsx
// import { useState, useEffect } from "react"
import Image from "next/image"
import { useRouter } from "next/router"
import Link from "next/link"
import { 
    Searchbar, 
} from "@/src/components"


export const Navbar = () => {    
    // const [locale, setLocale] = useState("en")
    const router = useRouter()

    // const routes = [
    //     { localeVar: "Home", name: "Home", path: "/" },
    // ]

    // useEffect(() => {
    //     const sysLang = document.cookie.split("; ")
    //         .find((row) => row.startsWith("lang="))?.split("=")[1] || "en"
    //     setLocale(sysLang)
    // }, [])

    // const handleLocaleChange = (target) => {
    //     document.cookie = `lang=${target}`
    //     setLocale(target)
    // }

    const handleSourceCodeClick = () => {
        const url = process.env.NEXT_PUBLIC_SOURCE_CODE_URL
        window.open(url, "_blank")
    }

    const handleJoinDiscordClick = () => {
        const url = process.env.NEXT_PUBLIC_DISCORD_URL
        window.open(url, "_blank")
    }


    return (
        <nav className="
            sm:flex sm:flex-row sm:items-center sm:px-6 lg:px-8 sm:pb-0
            relative
            flex flex-col 
            px-2 min-h-16 w-full
            bg-gray-800
            sticky top-0 z-10
            pb-3
            "
        >
            <div className="flex items-center py-2 sm:py-0">
                <Link href="/"> 
                    <Image src="/favicon.ico" alt="can it run doom?" width={40} height={40} />
                </Link>

                <div className="flex order-1 ml-10">
                    {/* <select
                        className="dropdown nav-btn mr-10"
                        value={locale}
                        onChange={(e) => handleLocaleChange(e.target.value)}
                    >
                        {["en", "fr", "es"].map((loc) => (
                            <option key={`locale-${loc}`} value={loc}>
                                {loc.toUpperCase()}
                            </option>
                        ))}
                    </select> */}

                    <div className="nav-icon" onClick={handleSourceCodeClick}>
                        <Image
                            src="/icons/github-mark-white.png"
                            alt="source code"
                            width={24}
                            height={24}
                            className="rounded-full sm:ml-4 cursor-pointer"
                        />
                    </div>
                    <div className="nav-icon ml-5" onClick={handleJoinDiscordClick}>
                        <Image
                            src="/icons/discord-48.png"
                            alt="discord server"
                            width={24}
                            height={24}
                            className="rounded-full sm:ml-4 cursor-pointer"
                        />
                    </div>
                </div>
            </div>

            <Searchbar className="order-2" />

            <div className="flex items-end order-3 gap-3">
                { router.pathname !== "/" &&
                    <Link href="/" className="doom-btn">
                            Home
                    </Link>
                }
                <Link 
                    href="/manage-entries"
                    className="doom-btn"
                >
                        Add New
                </Link>
            </div>
        </nav>
    )
}
